# Learn Posture

use machine learning to recognize robot's posture (following the example in [scikit-learn-intro.ipynb](./scikit-learn-intro.ipynb) )

## 1. Data collection

We have colleceted data before, you need to add new data if you want to add new posture.

* the dateset are in *robot_pose_data* folder
* each file contains the data belongs to this posture, e.g. the data in *Back* file are collected when robot was in "Back" posture
* the data file can be load by ```pickle```, e.g. ```pickle.load(open('Back'))```, the data is a list of feature data
* the features (e.g. each row of the data) are ['LHipYawPitch', 'LHipRoll', 'LHipPitch', 'LKneePitch', 'RHipYawPitch', 'RHipRoll', 'RHipPitch', 'RKneePitch', 'AngleX', 'AngleY'], where 'AngleX' and 'AngleY' are body angle (e.g. ```Perception.imu```) and others are joint angles.

## 2. Data preprocessing

In [1]:
%pylab inline
import pickle
from os import listdir, path
import numpy as np
from sklearn import svm, metrics

ROBOT_POSE_DATA_DIR = 'robot_pose_data'

Populating the interactive namespace from numpy and matplotlib


In [2]:
classes = listdir(ROBOT_POSE_DATA_DIR)
print classes

['Knee', 'Back', 'Crouch', 'Belly', 'Right', 'Sit', 'Frog', 'Left', 'StandInit', 'HeadBack', 'Stand']


In [3]:
def load_pose_data(i):
    '''load pose data from file'''
    data = []
    target = []
    # YOUR CODE HERE
    
    filename = path.join(ROBOT_POSE_DATA_DIR, classes[i])
    data = pickle.load(open(filename))
    target = [i] * len(data)
    return data, target

In [4]:
# load all the data
all_data = []
all_target = []
# YOUR CODE HERE
for x in range(0, len(classes)):
    cur_data, cur_target = load_pose_data(x)
    all_data += cur_data;
    all_target += cur_target;
print 'total number of data', len(all_data)

total number of data 222


In [5]:
# shuffule data
permutation = np.random.permutation(len(all_data))
n_training_data = int(len(all_data) * 0.7)
training_data = permutation[:n_training_data]

## 3. Learn on training data

In scikit-learn, an estimator for classification is a Python object that implements the methods fit(X, y) and predict(T). An example of an estimator is the class sklearn.svm.SVC that implements support vector classification.

In [6]:
clf = svm.SVC(gamma=0.001, C=100.)

### learning

In [10]:
clf.fit(all_data, all_target)

ValueError: Expected 2D array, got 1D array instead:
array=[103.  87. 176. 158.  60.  49.  33.  68. 116.  34.  66. 217. 126. 115.
 194. 184. 152. 111. 193. 106. 134. 107. 109. 212. 198. 161.  50.  12.
  70. 144.  42. 209. 191. 164.  27. 214. 140.  17. 129. 127.  69. 159.
 208. 179. 104.  13. 175. 213.  81. 192. 203. 145.  16.   5.  46.  45.
 167. 187.   7.  61. 102.  78. 201. 162. 131.  31.  30.  35.  37.  74.
 138.  47.  63. 221.   1. 190.   0. 188.  26.  73.  29. 139. 101. 132.
 211. 121.  59. 146. 204. 105.  54. 149. 130. 196. 199. 142. 210. 166.
  72. 178. 189. 220.  80.   2. 168. 216. 197. 150. 148. 112.  36.  52.
 133. 151. 114.  38.  43.  51.  18.  57.   4.  40. 128.  11. 186.  95.
  98.   9.  99. 123.   8.  53.  58.  93.  84. 170. 185.  71. 218. 120.
 202. 147.  55.  90.  41.  76. 125. 171. 182. 169. 154. 177. 157.  21.
 155.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

### predicting

In [26]:
clf.predict(all_data[-1:]), all_target[-1:]

(array([10]), [10])

In [27]:
def evaluate(expected, predicted):
    print("Classification report:\n%s\n" % metrics.classification_report(expected, predicted))

    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

In [33]:
expected = []
predicted = []
# YOUR CODE HERE
expected = all_target
predicted = clf.predict(all_data)

evaluate(expected, predicted)

Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        23
           2       0.97      1.00      0.98        30
           3       1.00      1.00      1.00        19
           4       1.00      0.91      0.95        11
           5       1.00      1.00      1.00        26
           6       1.00      1.00      1.00        10
           7       1.00      1.00      1.00        20
           8       1.00      1.00      1.00        52
           9       1.00      1.00      1.00        10
          10       1.00      1.00      1.00        11

   micro avg       1.00      1.00      1.00       222
   macro avg       1.00      0.99      0.99       222
weighted avg       1.00      1.00      1.00       222


Confusion matrix:
[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0 23  0  0  0  0  0  0  0  0  0]
 [ 0  0 30  0  0  0  0  0  0  0  0]
 [ 0  0  0 19  0  0  0  0  0  0  0]
 

## 4. Evaluate on the test data

In [29]:
expected = []
predicted = []
# YOUR CODE HERE
expected = all_target
predicted = clf.predict(all_data)

evaluate(expected, predicted)

Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        23
           2       0.97      1.00      0.98        30
           3       1.00      1.00      1.00        19
           4       1.00      0.91      0.95        11
           5       1.00      1.00      1.00        26
           6       1.00      1.00      1.00        10
           7       1.00      1.00      1.00        20
           8       1.00      1.00      1.00        52
           9       1.00      1.00      1.00        10
          10       1.00      1.00      1.00        11

   micro avg       1.00      1.00      1.00       222
   macro avg       1.00      0.99      0.99       222
weighted avg       1.00      1.00      1.00       222


Confusion matrix:
[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0 23  0  0  0  0  0  0  0  0  0]
 [ 0  0 30  0  0  0  0  0  0  0  0]
 [ 0  0  0 19  0  0  0  0  0  0  0]
 

## 5. Deploy to the real system

We can simple use `pickle` module to serialize the trained classifier.

In [30]:
import pickle
ROBOT_POSE_CLF = 'robot_pose.pkl'
pickle.dump(clf, open(ROBOT_POSE_CLF, 'w'))

Then, in the application we can load the trained classifier again.

In [32]:
clf2 = pickle.load(open(ROBOT_POSE_CLF))
clf2.predict(all_data[-1:]), all_target[-1]

(array([10]), 10)